baseURL = ""
relativeURLs = true

languageCode = "de-de"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
[languages]
  [languages.de]
    weight = 1
    languageName = "DE"
    title = "evcc - Sonne tanken â˜€ï¸ğŸš˜ - PV-Ãœberschussladen fÃ¼r steuerbare Wallboxen"
  [languages.en]
    weight = 2
    languageName = "EN"
    title = "evcc - Solar Charging â˜€ï¸ğŸš˜ - Connects Your EV Charger With Your PV System"
[site]
  [params]
  description = "evcc ermÃ¶glicht es Elektrofahrzeuge mit mÃ¶glichst viel selbsterzeugten Solarstrom zu laden."

[minify]
  disableSVG = true
  disableHTML = true

[security]
  [security.funcs]
    getenv = ["SLACK_INVITE_URL"]