baseURL = ""
relativeURLs = true

languageCode = "de-de"
defaultContentLanguage = "de"
[languages]
  [languages.de]
    weight = 1
    languageName = "Deutsch"
    title = "evcc - Sonne tanken â˜€ï¸ğŸš˜ - PV-Ãœberschussladen fÃ¼r steuerbare Wallboxen"
  [languages.en]
    weight = 2
    languageName = "English"
    title = "evcc - Sunny tank â˜€ï¸ğŸš˜ - PV Surplus Charging for compatible Wallboxes"
[site]
  [params]
  description = "evcc ermÃ¶glicht es Elektrofahrzeuge mit mÃ¶glichst viel selbsterzeugten Solarstrom zu laden."

[minify]
  disableSVG = true
  disableHTML = true

[security]
  [security.funcs]
    getenv = ["SLACK_INVITE_URL"]