baseURL = ""
relativeURLs = true

languageCode = "de-de"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
[languages]
  [languages.de]
    weight = 1
    languageName = "DE"
    title = "evcc - Sonne tanken â˜€ï¸ğŸš˜ - PV-Ãœberschussladen fÃ¼r steuerbare Wallboxen"
    [languages.de.params]
      docsUrl = "https://docs.evcc.io/docs/Home"
      blogUrl = "https://docs.evcc.io/blog"
  [languages.en]
    weight = 2
    languageName = "EN"
    title = "evcc - Solar Charging â˜€ï¸ğŸš˜ - Connects Your EV Charger With Your PV System"
    [languages.en.params]
      docsUrl = "https://docs.evcc.io/en/docs/Home"
      blogUrl = "https://docs.evcc.io/en/blog"
[site]
  [params]
  description = "evcc ermÃ¶glicht es, Elektrofahrzeuge mit mÃ¶glichst viel selbsterzeugtem Solarstrom zu laden."

[minify]
  disableSVG = true
  disableHTML = true

[security]
  [security.funcs]
    getenv = ["SLACK_INVITE_URL"]
