baseURL = ""
relativeURLs = true
languageCode = "de-de"
title = "evcc - Sonne tanken â˜€ï¸ğŸš˜ - PV-Ãœberschussladen fÃ¼r steuerbare Wallboxen"

[site]
  [params]
  description = "evcc ermÃ¶glicht es Elektrofahrzeuge mit mÃ¶glichst viel selbsterzeugten Solarstrom zu laden."

[minify]
  disableSVG = true
  disableHTML = true